name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn run ci
    - name: Create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
    - name: Setup GIT
      run: |
        git switch -c master
        git config --global user.email "marjantanevski@gmail.com"
        git config --global user.name "Tanevski"
          
    - name: Bump version
      run: |
        yarn version --new-version ${GITHUB_REF#"refs/tags/"}
        git push https://${{secrets.GPR_TOKEN}}@github.com/Tanevski3/tweener
    - name: Publish
      run: yarn publish --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version
